name: build QT

on:
  push:
    branches: [ master, "2.0", "2.1-milestones" ]
  pull_request:
    branches: [ master, "2.0" ]
  workflow_dispatch:
#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:

    runs-on: self-hosted
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TESTING: [testing]
        TARGET: [pi-buster, pi-bullseye] # <-- Add targets here!

    steps:
    - name: fetch
  image: arm32v6/alpine:3.12
  commands:
 - name: build
  image: plugins/docker
  environment:
    CLOUDSMITH_API_KEY:
      from_secret: CLOUDSMITH_API_KEY
  settings:
      repo: openhd/qopenhd
      dry_run: true
      username:
        from_secret: docker_openhd_username
      password:
        from_secret: docker_openhd_password
      dockerfile: Dockerfile-armhf-raspbian-bullseye
      build_args_from_env:
        - CLOUDSMITH_API_KEY

    - name: Pack file
      uses: 'actions/upload-artifact@v2'
      with:
        name: "${{ env.artifact_name }}"
        path: |
          ./deploy/*
          if-no-files-found: error
